### ISSUE TITLE
执行完无法导出，请问怎么解决？

### ISSUE THREAD

**Issue by 1063122023** [newcodor/coremail_address_list_export#1]
![image](https://user-images.githubusercontent.com/41679105/169253023-5ada013a-4a82-476e-bfc2-8ca5579390ef.png)

**Comment by newcodor** [comment]
这个地方连获取Total 数量都没有显示，有以下几种可能:
(1) 您使用的cookie 参数错误或无效。
(2) 网络故障。可以使用-proxy 参数代理到您的抓包软件如burpsuit、fiddler等观察网络连通性。
(3) coremail 的接口格式已发生变化,可以使用-proxy 参数代理到您的抓包软件如burpsuit、fiddler等观察http请求、响应来确认这种情况,如果出现了该问题,那意味着该工具已失效，您可以提交请求样例、等待作者更新或另寻其他工具使用。
